name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run test suite
    runs-on: self-hosted
    container: node:16
    # env:
    steps:
    - name: Checkout code
      run: echo "Hello from node"