name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    container: maven:latest
    # env:
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: mvn compile; mvn --no-transfer-progress test; mvn package; mvn validate
    - uses: actions/upload-artifact@v4
      with:
        name: maven-build
        path: target
  deploy:
    name: Deploy jar
    runs-on: self-hosted
    container: ansible/ansible:ubuntu1604py3
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: maven-build
        path: /tmp/artifact
    - run: ls /tmp/artifact
      