name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: self-hosted
    container: node:16
    # env:
    steps:
    - name: Checkout code
      uses: echo "Hello from node"