name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run test suite
    runs-on: self-hosted
    container: maven:latest
    # env:
    steps:
    - name: Checkout code
      run: actions/checkout@v4
    - run: mvn test