name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    container: maven:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: mvn compile; mvn --no-transfer-progress test; mvn package; mvn validate
    - uses: actions/upload-artifact@v4
      with:
        name: maven-build
        path: target
  deploy:
    name: Deploy jar
    runs-on: self-hosted
    container: node:latest
    env:
      DB_URL: jdbc:mysql://localhost:3306/yourdatabase
      DB_USERNAME: yourusername
      DB_PASSWORD: yourpassword
    steps:
    - run: apk install --nocache ansible
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: maven-build
        path: /tmp/artifact
    - run: ls /tmp/artifact
      